Fix issue for the package org.jlab.clas.clas.math.FastMath and cache some sine and cosine calculations in DC reconstruction and forward tracking
JeffersonLab/clas12-offline-software pull request #1084
Opened 2023-03-06 22:13 UTC by tongtongcao

Overall, there are two updates for this PR:
1) Fix issue for the package org.jlab.clas.clas.math.FastMath
The file describes the issue, and effects on tracking results.
[issue for the package FastMath.pdf](https://github.com/JeffersonLab/clas12-offline-software/files/10903247/issue.for.the.package.FastMath.pdf)
2) Cache sine and cosine calculations in DC reconstruction and forward tracking
It will not affect tracking results, but will save running time.
As expected, the plots shows that changes due to precision of float for tracking results is negligible.
[diff of RECParticle.pdf](https://github.com/JeffersonLab/clas12-offline-software/files/10903290/diff.of.RECParticle.pdf)

The update 1 increases running time, while the update 2 reduces running time. As my quick test, the running time with the two updates almost has no change comparing to before updates.

2023-03-06 22:24 UTC, gavalian submitted a review, later dismissed
This looks good. Hopefully, it will speed up the code some. ;-)

2023-03-06 22:28 UTC, baltzell commented
Don't you want to instead do, for example,

`public static final double SIN25 = SOME_PRECISE_AND_SLOW_MATH_LIBRARY.sin(25)?
`

Instead of leaving others to wonder where the numbers came from?

2023-03-07 14:20 UTC, tongtongcao commented
> Don't you want to instead do, for example,
> 
> `public static final double SIN25 = SOME_MOST_ACCURATE_BUT_SLOW_MATH_LIBRARY.sin(25)? `
> 
> Instead of leaving others to wonder where the numbers came from?

2023-03-07 14:21 UTC, tongtongcao commented
> > Don't you want to instead do, for example,
> > `public static final double SIN25 = SOME_MOST_ACCURATE_BUT_SLOW_MATH_LIBRARY.sin(25)? `
> > Instead of leaving others to wonder where the numbers came from?

2023-03-07 14:26 UTC, tongtongcao commented
With consideration of precision of other constant parameters, precision %.8f for them should be enough.

2023-03-07 14:53 UTC, zieglerv submitted a review, later dismissed

2023-03-07 15:06 UTC, baltzell commented
nothing to do with precision, just transparency

2023-03-07 15:11 UTC, raffaelladevita requested changes
I agree with Nathan's suggestion: it's not going to change the result but it would improve readability

2023-03-07 15:19 UTC, baltzell commented
unless we're worried about Java breaking its math library;)

2023-03-07 16:08 UTC, tongtongcao commented
Okay. Please check update for assignment of constant parameters with math libraries.

2023-03-16 23:53 UTC, raffaelladevita approved these changes

2023-03-16 23:53 UTC, merged