Fttrk dev
JeffersonLab/clas12-offline-software pull request #798
Opened 2022-02-21 08:49 UTC by afilippi67

update with full corrections for Fall18 Transition Table and general fixes to tracking algorithm (hits from both TRK detectors stored in banks, tuning of discontinuities in strip numbering, multiple tracks matching with one/two TRK hits).
To be merged to iss642-fttrkDev branch as first step.

2022-02-21 14:19 UTC, raffaelladevita requested changes

2022-02-21 15:42 UTC, afilippi67 commented on build-coatjava.sh
> +mvn='/usr/local/apache-maven-3.6.3/bin/mvn'
ok, this is inessential, please ignore the pull

2022-02-21 16:05 UTC, afilippi67 commented on etc/bankdefs/hipo4/ft.json
> +              {"name":"energy",    "type":"F", "info":"Hit Energy" },
yes, cluster energy

2022-02-21 16:06 UTC, afilippi67 commented on etc/bankdefs/hipo4/ft.json
> +             {"name":"Cluster2ID",  "type":"S", "info":"ID of the top layer cluster in the Cross"}
ok

2022-02-21 16:07 UTC, afilippi67 commented on reconstruction/ft/src/main/java/org/jlab/rec/ft/FTEBEngine.java
> +    public static H1F h500 = new H1F("Time Difference FTCAL-response", 100, 0., 200.);
they are filled somewhere else in the code: they could be defined in the class where they are filled. Or they could be dropped altogether, as used only for diagnostic purposes (and indeed their filling is flagged)

2022-02-21 16:07 UTC, afilippi67 commented on reconstruction/ft/src/main/java/org/jlab/rec/ft/FTEBEngine.java
> +
ok, I wasn't aware of this folder. Diagnostic histograms could also be moved here.

2022-02-21 16:07 UTC, afilippi67 commented on reconstruction/ft/src/main/java/org/jlab/rec/ft/FTEBEngineSingleEvent.java
> +public class FTEBEngineSingleEvent extends ReconstructionEngine {
the purpose is to analyze single events dropping some cumulative histograms. It can be excluded from the pull.

2022-02-21 16:07 UTC, afilippi67 commented on reconstruction/ft/src/main/java/org/jlab/rec/ft/FTResponse.java
> +    private int    _trkDet;          // number of TRK detector (0,1)
yes, it could be worth for the sake of clarity. It comes from legacy from old code.

2022-02-21 16:08 UTC, afilippi67 commented on reconstruction/ft/src/main/java/org/jlab/rec/ft/FTResponse.java
> +    private float  _crTime;            // provisional: detector time (for crosses only: the location in the bank is overwritten)
these were used as support variables when the energy/time banks were used provisionally for some other variables. Done some time ago and forgotten, must be revised to see if everything is consistent dropping these variables which are no longer used (there is -should be- no difference but a check needs to be done)

2022-02-21 16:08 UTC, afilippi67 commented on reconstruction/ft/src/main/java/org/jlab/rec/ft/FTParticle.java
> +                            FTEBEngine.h600.fill(response.getPosition().mag()/PhysicsConstants.speedOfLight());
yes it can be removed from the general reconstruction flux and/or put in test

2022-04-28 11:14 UTC, raffaelladevita approved these changes

2022-05-02 19:57 UTC, merged