Trajectory banks modifications: new edge variable, dx in DC banks and new HBT bank
JeffersonLab/clas12-offline-software pull request #959
Opened 2022-10-01 22:35 UTC by raffaelladevita

Added dx to DC trajectory bank for dE/dx calculation in EB. Added HB-tracking trajectory bank, to allow the standardization of the EB track to hit matching. Added to ALL trajectory banks, the variable "edge", defined as minimum distance of the trajectory point from the edges of the layer, to facilitate fiducial cuts.

The changes to the code include:
- clas-geometry:
  - new Trap3D class to describe generic trapezoids (used to describe the DC and FTOF layers for the trajectory calculation);
  - new methods isInside() and distanceToEdge() in Cylindrical3D, Sector3D, Triangle3D and Trap3D, to facilitate checking whether the trajectory point is inside the surface boundary and calculate the distance from the edge;
  - definition of the trajectory surface in FMT and ECAL;
  - new methods to retrieve the ECAL superlayer scintillator thickness.
- clas-jcsg:
  - definition of trajectory surface for DC and FTOF.
- cvt:
  - modified BMTGeometry, SVTGeometry, StateVec and Track classes, to compute and handle the new quantity "edge";
  - modified RecoBankWriter and associated json file to add "edge" to the CVT trajectory banks;
  - BUG FIX: conversion of CND and CTOF paddle length from cm to mm; this information was not used before so the bug had no consequences.
- dc:
  - restructuring of Surface class to handle the layer contours and support the calculation of "dc" and "edge";
  - restructuring and cleanup of TrajectorySurfaces
  - simplification of trajectory calculation in Trajectory class: now DC trajectories are calculated in the CLAS12 frame instead of the TSCS;
  - calculation of HB trajectory with modifications to RecoBankWriter and associated jsons;
  - propagation of changes to engines and various refactoring.

Closes #955 and #956. Also related to #704

2022-10-06 11:44 UTC, raffaelladevita commented
![Screen Shot 2022-10-06 at 13 39 33](https://user-images.githubusercontent.com/7524926/194303903-78d0fa4d-2faa-4e1c-a873-a53254b460c2.png)
For illustration, the two plots show the FTOF-1B trajectory from real data with no cuts (left) and with a 10cm cut on the "edge" variable (right). The plots are for sector 1 only and the coordinates are in the tilted frame

2022-10-06 21:00 UTC, zieglerv requested changes
The call this.addTrajectoryPoint(tPars[0], tPars[1], tPars[2], -tPars[3], -tPars[4], -tPars[5], tPars[2]-v.z(), Math.abs((tPars[2]-v.z())*b[2]), surface) at line 219 in reconstruction/dc/src/main/java/org/jlab/rec/dc/trajectory/Trajectory.java 
is using the parameters obtained in the lab frame.
path = tPars[2]-v.z() 
and bdl = Math.abs((tPars[2]-v.z())*b[2]) = path*By are only correct for tracks along z in the Tilted Sector Coordinate frame, I think.

2022-10-23 21:19 UTC, raffaelladevita commented
The changes discussed at the software meeting were implemented:
- the "edge" variable is now a signed distance from the surface boundary (>0 if the trajectory point is inside the boundary, <0 if outside, -99 if the boundary is undefined). As an example, the following plot should the trajectories with edge<-10 cm for ECinner.
![image](https://user-images.githubusercontent.com/7524926/197418496-9235450d-55ab-4f55-816d-c1d917c98733.png)
- trajectory points with edge<-99 are not saved
- the DC boundary was modified to be the AND of both super layers in a region. See the following plot.
![image](https://user-images.githubusercontent.com/7524926/197418602-dbf29b95-7846-498f-bcfb-0a62e7ee7c1a.png)

The effect of dropping tracks with vertex downstream with respect to the HTCC sphere was further investigated, finding that the number of identified charged particles when running AI tracking is unchanged when running AI tracking, and drops by less than % when running conventional tracking.

2022-10-24 22:07 UTC, zieglerv approved these changes

2022-10-26 23:43 UTC, merged